name: Initialize GitHub Pages

on:
  # 只在手动触发时运行
  workflow_dispatch:

# 设置权限
permissions:
  contents: read
  pages: write
  id-token: write

# 确保同时只运行一个部署
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # 初始化GitHub Pages
  init:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置Pages
        uses: actions/configure-pages@v4

      - name: 上传空工件
        uses: actions/upload-pages-artifact@v3
        with:
          path: "."

      - name: 部署到GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          enablement: true
